eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:9000/eureka/
  instance:
    hostname: localhost
server:  port: 9005
spring:  application:
    name: bankcheck      
  